### ISSUE TITLE
matplotlib setup

### ISSUE THREAD

**Issue by hschellman** [DUNE/dune_plot_style#48]
I did a git clone on the repository, worked fine. 

then a 

`pip install -e .` 

I can import the package just fine but none of the environmental are set up so it doesn't find the style sheets.

I also tried doing a pip install with the `--user` command, nothing shows up in `~/.local` where it should.

could a pipspert please look at this and make some suggestions on how to make this work with the usual pip install --user and actually get the correct config? 

And yes, using venv, pip, conda and ups is going to make this a pain.

**Comment by hschellman** [comment]
So, where is the code that actually tells matplotlib where the style sheets are?  The only export command I could find in the stack was to the include directory for C++ code.

**Comment by hschellman** [comment]
So I tried running the matplotlib example instead of trying my own script. 

what I get is: 

python example.py
Traceback (most recent call last):
  File "/Users/schellma/Dropbox/Apps/dune_plot_style/examples/matplotlib/example.py", line 220, in <module>
    Hist1D(pdf)
  File "/Users/schellma/Dropbox/Apps/dune_plot_style/examples/matplotlib/example.py", line 36, in Hist1D
    dunestyle.Simulation()
AttributeError: module 'dunestyle.matplotlib' has no attribute 'Simulation'

So if I hack my python path by hand to point to the matplotlib/python directory I get to:

Traceback (most recent call last):
  File "/Users/schellma/Dropbox/Apps/dune_plot_style/examples/matplotlib/example.py", line 18, in <module>
    import dunestyle.matplotlib as dunestyle
  File "/Users/schellma/Dropbox/Apps/dune_plot_style/src/matplotlib/python/dunestyle.py", line 33, in <module>
    enable()
  File "/Users/schellma/Dropbox/Apps/dune_plot_style/src/matplotlib/python/dunestyle.py", line 24, in enable
    path = os.path.join(os.environ['MPLCONFIGDIR'].split(os.pathsep)[0], "dune.mplstyle")
  File "/Users/schellma/miniconda/envs/ccqe/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'MPLCONFIGDIR'

This looks as if the __init__ is not being set.

To reiterate 

pip install -e .

# must do this or can't find simulation
export PYTHONPATH=/Users/schellma/Dropbox/Apps/dune_plot_style/src/matplotlib/python

cd examples/matplotlib

python example.py


Traceback (most recent call last):
  File "/Users/schellma/Dropbox/Apps/dune_plot_style/examples/matplotlib/example.py", line 18, in <module>
    import dunestyle.matplotlib as dunestyle
  File "/Users/schellma/Dropbox/Apps/dune_plot_style/src/matplotlib/python/dunestyle.py", line 33, in <module>
    enable()
  File "/Users/schellma/Dropbox/Apps/dune_plot_style/src/matplotlib/python/dunestyle.py", line 24, in enable
    path = os.path.join(os.environ['MPLCONFIGDIR'].split(os.pathsep)[0], "dune.mplstyle")
  File "/Users/schellma/miniconda/envs/ccqe/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'MPLCONFIGDIR'


which looks as if the __init__  is never being called as it does set that environmental.

**Comment by olantwin** [comment]
Sorry for the late reaction.

Maybe @admlw has some more ideas as to why this happens, but for me (and in the CI) the examples work correctly when the package is installed using:

```bash
pip install $PATH_TO_PACKAGE
```

Note, that I do not pass the `-e` option. A priore this also should work with `--user`.

Concerning the multiple package managers, for now `pip` and `ups` are the only ones we target. `conda` is only used to set up ROOT for the CI.

**Comment by chenel** [comment]
Agreed, I think the `-e` flag is the culprit here---that installs in "editable" mode, which doesn't carry out all the installation steps (in particular, it doesn't move everything into `~/.local`).

@hschellman we could probably make this work in editable mode if needed, but it would require goofing around with the `setup.cfg` (which is the closest thing to black magic Python offers).  If that's an important part of your workflow for some reason we can certainly prioritize it, but if not, I'd suggest just dropping that and seeing if everything "just works" 😄

**Comment by hschellman** [comment]
I got it to work but was a bit confused by the complicated path needed.

git clone ...

cd dune_plot_style

pip install $PWD/../dune_plot_style

doing pip install from the directory above does not work as it doesn't look into the directory.  

I was expecting it to work from within the directory.  I'm not certain if it is possible to set it up so that one doesn't have to go one layer up but it would help if the instructions were more explicit about where one has to be to make the command and what path you need to use in the setup.

**Comment by olantwin** [comment]
> Advanced topic - any way to get the DUNE logo instead of mono-color DUNE in the plots?

We debated this briefly to improve the recognisability, but failed to find a workable solution for matplotlib and ROOT: https://github.com/DUNE/dune_plot_style/issues/40 . If we can solve the technical issues, this would be worth revisiting for a future update of the style.

**Comment by olantwin** [comment]
> Can you update the doc to be very explicit about where you do things?

I can't reproduce the issue with the installation directory. For me it works regardless of whether I'm in the root of the repository or in a different one (e.g. two directories up).

In the README we install from the root of the directory, which seems OK on my machine:

```bash
cd /path/to/install/area/dune_plot_style
python3 -m pip install .
```

Unless we can confirm that it doesn't work particular directories, I don't think we need to be any more specific than that.
For reference, I do this in a fresh virtual environment, as I have too many other python packages flying around.

**Comment by hschellman** [comment]
Ok, I;m now running into the fact that DUNE preliminary at the top is overwriting my legend.  Any idea how to move a legend down in Matplotlib?


On Apr 18, 2023, at 9:04 AM, Oliver Lantwin ***@***.******@***.***>> wrote:


[This email originated from outside of OSU. Use caution with links and attachments.]


Advanced topic - any way to get the DUNE logo instead of mono-color DUNE in the plots?

We debated this briefly to improve the recognisability, but failed to find a workable solution for matplotlib and ROOT: #40<https://github.com/DUNE/dune_plot_style/issues/40> . If we can solve the technical issues, this would be worth revisiting for a future update of the style.

**Comment by chenel** [comment]
> Ok, I'm now running into the fact that DUNE preliminary at the top is overwriting my legend.  Any idea how to move a legend down in Matplotlib?

In general I think we'd prefer to support 'how-to' things that aren't "issues" per se on the #plot-style-help Slack channel, but for today: see the "other parameters" section of https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.legend.html#matplotlib.pyplot.legend (note specifically the `loc` keyword).
